import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import HeaderSidebar from "@/components/HeaderSidebar";
import "../globals.css"
import { LoadingProvider } from "@/hooks/context/LoadingContext";
import { NotificationProvider } from "@/hooks/context/NotificationContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div id="headerSidebar">
      <HeaderSidebar />
      {children}
    </div>
  );
}
